# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Naviclaude < Formula
  desc "TUI for managing Claude Code sessions across tmux"
  homepage "https://github.com/thbits/naviClaude"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thbits/naviClaude/releases/download/v0.2.1/naviclaude_0.2.1_darwin_amd64.tar.gz"
      sha256 "a1cc0ca80a9eb86339143bc2d6c88591667617beb9fb65f10824631cf488defa"

      define_method(:install) do
        bin.install "naviclaude"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thbits/naviClaude/releases/download/v0.2.1/naviclaude_0.2.1_darwin_arm64.tar.gz"
      sha256 "7bb46f981b3edfc48dccd2cde18412892fcd277335d705c21f232dfbac68d241"

      define_method(:install) do
        bin.install "naviclaude"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thbits/naviClaude/releases/download/v0.2.1/naviclaude_0.2.1_linux_amd64.tar.gz"
      sha256 "11b468dd02e4986c9dc3c0813a676ec113998a3cb96687acca4c450755647662"
      define_method(:install) do
        bin.install "naviclaude"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thbits/naviClaude/releases/download/v0.2.1/naviclaude_0.2.1_linux_arm64.tar.gz"
      sha256 "801d98d68473c5a4a1dd74c05e86c1a67342d7e4b7d1efbb875dd1b5b9291d18"
      define_method(:install) do
        bin.install "naviclaude"
      end
    end
  end

  test do
    system "#{bin}/naviclaude", "--version"
  end
end
