# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Naviclaude < Formula
  desc "TUI for managing Claude Code sessions across tmux"
  homepage "https://github.com/thbits/naviClaude"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thbits/naviClaude/releases/download/v0.1.1/naviclaude_0.1.1_darwin_amd64.tar.gz"
      sha256 "f6c6b1a71c9968733e0ca306f5fe3242e5b330191d45be3edbd0e5f55b38f703"

      define_method(:install) do
        bin.install "naviclaude"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thbits/naviClaude/releases/download/v0.1.1/naviclaude_0.1.1_darwin_arm64.tar.gz"
      sha256 "4944ad4adf8b49ccabb59ec16fda032e2e2240094eb9ef24beec162cdfb043ef"

      define_method(:install) do
        bin.install "naviclaude"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thbits/naviClaude/releases/download/v0.1.1/naviclaude_0.1.1_linux_amd64.tar.gz"
      sha256 "307380542a7b385a797c115ff807ee37e8a8e434b8a79d2187432db638d42797"
      define_method(:install) do
        bin.install "naviclaude"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thbits/naviClaude/releases/download/v0.1.1/naviclaude_0.1.1_linux_arm64.tar.gz"
      sha256 "16bb9fbbe0dda86c3016074603d092ffe813f45f93bafa66344d9c17490fe826"
      define_method(:install) do
        bin.install "naviclaude"
      end
    end
  end

  test do
    system "#{bin}/naviclaude", "--version"
  end
end
