# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Naviclaude < Formula
  desc "TUI for managing Claude Code sessions across tmux"
  homepage "https://github.com/thbits/naviClaude"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thbits/naviClaude/releases/download/v0.2.0/naviclaude_0.2.0_darwin_amd64.tar.gz"
      sha256 "df19d3fd69eee1c0820a135fc6d785fd72502cf0d3a03735580ac5c6419f0009"

      define_method(:install) do
        bin.install "naviclaude"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thbits/naviClaude/releases/download/v0.2.0/naviclaude_0.2.0_darwin_arm64.tar.gz"
      sha256 "68e27fe2ab5bc7d26a5c2ba688d7dd5397a8c91731aeda64c7ae87df9d5056b7"

      define_method(:install) do
        bin.install "naviclaude"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thbits/naviClaude/releases/download/v0.2.0/naviclaude_0.2.0_linux_amd64.tar.gz"
      sha256 "4ac36f6edf13a17bb3da790b19522dd5729264168d1c80014754c1962d321ac5"
      define_method(:install) do
        bin.install "naviclaude"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thbits/naviClaude/releases/download/v0.2.0/naviclaude_0.2.0_linux_arm64.tar.gz"
      sha256 "aee1866866b0f9dd436258031f58e98880af557e6a85b500fb7570ffc2da63ff"
      define_method(:install) do
        bin.install "naviclaude"
      end
    end
  end

  test do
    system "#{bin}/naviclaude", "--version"
  end
end
